<?php
require_once '../config/config.php';
require_once '../includes/auth.php';
require_once '../includes/functions.php';
require_once '../includes/db.php';
require_once '../includes/admin_layout.php';

requireLogin();
requireRole(['admin']);

$currentUser = getCurrentUser();
$message = '';
$error = '';

// 获取系统设置
$systemSettings = [];
$settings = fetchAll("SELECT setting_key, value FROM settings");
foreach ($settings as $setting) {
    $systemSettings[$setting['setting_key']] = $setting['value'];
}

// 获取用户列表（用于密码重置）
$users = fetchAll("SELECT id, username, real_name, role FROM users WHERE status = 'active' ORDER BY username");

// 处理表单提交
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    if (isset($_POST['action'])) {
        switch ($_POST['action']) {
            case 'update_system':
                $systemName = trim($_POST['system_name']);
                $systemVersion = trim($_POST['system_version']);
                $maintenanceMode = isset($_POST['maintenance_mode']) ? 1 : 0;
                $sessionTimeout = intval($_POST['session_timeout']);

                if (empty($systemName)) {
                    $error = '系统名称不能为空';
                } else {
                    // 更新系统设置
                    $sql = "UPDATE settings SET value = ? WHERE setting_key = ?";
                    query($sql, [$systemName, 'system_name']);
                    query($sql, [$systemVersion, 'system_version']);
                    query($sql, [$maintenanceMode, 'maintenance_mode']);
                    query($sql, [$sessionTimeout, 'session_timeout']);

                    $message = '系统设置更新成功';
                }
                break;

            case 'backup_database':
                try {
                    $backupFile = 'backup_' . date('Y-m-d_H-i-s') . '.sql';
                    $backupPath = '../backups/' . $backupFile;

                    // 创建备份目录
                    if (!file_exists('../backups')) {
                        mkdir('../backups', 0755, true);
                    }

                    // 使用PHP直接连接数据库进行备份
                    $pdo = new PDO('mysql:host=' . DB_HOST . ';dbname=' . DB_NAME, DB_USER, DB_PASS);
                    $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);

                    $backup = "-- Database: " . DB_NAME . " Backup\n";
                    $backup .= "-- Date: " . date('Y-m-d H:i:s') . "\n";
                    $backup .= "-- Generated by Glass Inventory Management System\n\n";
                    
                    // 禁用外键检查
                    $backup .= "SET FOREIGN_KEY_CHECKS=0;\n\n";
                    
                    // 获取所有表名
                    $tables = $pdo->query("SHOW TABLES")->fetchAll(PDO::FETCH_COLUMN);

                    foreach ($tables as $table) {
                        // 添加表删除语句
                        $backup .= "DROP TABLE IF EXISTS `$table`;\n";
                        
                        // 获取表结构
                        $result = $pdo->query("SHOW CREATE TABLE `$table`")->fetch();
                        $backup .= $result[1] . ";\n\n";

                        // 获取表数据
                        $rows = $pdo->query("SELECT * FROM `$table`");
                        $insertData = [];
                        
                        foreach ($rows as $row) {
                            $cols = [];
                            foreach ($row as $key => $value) {
                                if (is_numeric($key)) continue; // Skip numeric keys from PDO::FETCH_BOTH
                                if ($value === null) {
                                    $cols[] = 'NULL';
                                } else {
                                    $cols[] = "'" . addslashes($value) . "'";
                                }
                            }
                            if (!empty($cols)) {
                                $insertData[] = "(" . implode(',', $cols) . ")";
                            }
                        }
                        
                        // 批量插入数据（每100条一批）
                        if (!empty($insertData)) {
                            $chunks = array_chunk($insertData, 100);
                            foreach ($chunks as $chunk) {
                                $backup .= "INSERT INTO `$table` VALUES " . implode(',', $chunk) . ";\n";
                            }
                        }
                        $backup .= "\n";
                    }
                    
                    // 获取视图定义（跳过有权限问题的视图）
                    try {
                        $views = $pdo->query("SHOW FULL TABLES WHERE Table_type = 'VIEW'")->fetchAll(PDO::FETCH_COLUMN);
                        foreach ($views as $view) {
                            try {
                                $backup .= "DROP VIEW IF EXISTS `$view`;\n";
                                $result = $pdo->query("SHOW CREATE VIEW `$view`")->fetch();
                                // 移除DEFINER信息以避免权限问题
                                $createView = preg_replace('/DEFINER=`[^`]+`@`[^`]+`\s+/', '', $result[1]);
                                $backup .= $createView . ";\n\n";
                            } catch (Exception $e) {
                                $backup .= "-- 跳过视图 $view (权限问题): " . $e->getMessage() . "\n\n";
                            }
                        }
                    } catch (Exception $e) {
                        $backup .= "-- 跳过视图备份: " . $e->getMessage() . "\n\n";
                    }
                    
                    // 恢复外键检查
                    $backup .= "SET FOREIGN_KEY_CHECKS=1;\n";
                    
                    if (file_put_contents($backupPath, $backup)) {
                        $message = '数据库备份成功：' . $backupFile;
                    } else {
                        $error = '备份文件写入失败';
                    }
                    
                } catch (Exception $e) {
                    $error = '数据库备份失败：' . $e->getMessage();
                }
                break;

            case 'clear_logs':
                $daysToKeep = intval($_POST['days_to_keep']);
                if ($daysToKeep < 1) $daysToKeep = 30;
                
                $cutoffDate = date('Y-m-d', strtotime("-{$daysToKeep} days"));
                $deletedCount = query("DELETE FROM inventory_transactions WHERE DATE(transaction_time) < ?", [$cutoffDate]);
                
                $message = "已清理 {$daysToKeep} 天前的日志，共删除 {$deletedCount} 条记录";
                break;

            case 'reset_password':
                $userId = intval($_POST['user_id']);
                $newPassword = $_POST['new_password'];
                
                if ($userId <= 0 || empty($newPassword)) {
                    $error = '请选择用户并输入新密码';
                } elseif (strlen($newPassword) < 6) {
                    $error = '密码长度不能少于6位';
                } else {
                    $hashedPassword = password_hash($newPassword, PASSWORD_DEFAULT);
                    query("UPDATE users SET password = ?, updated_at = NOW() WHERE id = ?", [$hashedPassword, $userId]);
                    
                    $user = fetchRow("SELECT username FROM users WHERE id = ?", [$userId]);
                    $message = '用户 ' . $user['username'] . ' 的密码重置成功';
                }
                break;
        }
    }
}

// 获取备份文件列表
$backupFiles = [];
if (file_exists('../backups')) {
    $backupFiles = array_diff(scandir('../backups'), array('.', '..'));
    rsort($backupFiles); // 按时间倒序
}

// 获取系统统计信息
$stats = [
    'total_users' => fetchOne("SELECT COUNT(*) FROM users") ?: 0,
    'total_packages' => fetchOne("SELECT COUNT(*) FROM glass_packages") ?: 0,
    'total_transactions' => fetchOne("SELECT COUNT(*) FROM inventory_transactions") ?: 0,
    'database_size' => fetchOne("SELECT ROUND(SUM(data_length + index_length) / 1024 / 1024, 2) FROM information_schema.tables WHERE table_schema = '" . DB_NAME . "'") ?: 0,
    'active_users' => fetchOne("SELECT COUNT(*) FROM users WHERE status = 1") ?: 0,
    'storage_packages' => fetchOne("SELECT COUNT(*) FROM glass_packages WHERE status = 'in_storage'") ?: 0,
];
$additionalCSS=['../assets/css/admin/settings.css'];
ob_start();
?>
<div class="settings-container">
    <!-- 系统统计概览 - 始终显示 -->
    <div class="dashboard-card">
        <h3>📊 系统统计概览</h3>
        <div class="settings-stats-grid">
            <div class="settings-stat-item">
                <div class="stat-icon">👥</div>
                <div class="stat-content">
                    <div class="stat-value"><?php echo $stats['total_users']; ?></div>
                    <div class="stat-label">用户总数</div>
                </div>
            </div>
            <div class="settings-stat-item">
                <div class="stat-icon">✅</div>
                <div class="stat-content">
                    <div class="stat-value"><?php echo $stats['active_users']; ?></div>
                    <div class="stat-label">活跃用户</div>
                </div>
            </div>
            <div class="settings-stat-item">
                <div class="stat-icon">📦</div>
                <div class="stat-content">
                    <div class="stat-value"><?php echo $stats['total_packages']; ?></div>
                    <div class="stat-label">总包数</div>
                </div>
            </div>
            <div class="settings-stat-item">
                <div class="stat-icon">🏪</div>
                <div class="stat-content">
                    <div class="stat-value"><?php echo $stats['storage_packages']; ?></div>
                    <div class="stat-label">库存包数</div>
                </div>
            </div>
            <div class="settings-stat-item">
                <div class="stat-icon">📋</div>
                <div class="stat-content">
                    <div class="stat-value"><?php echo $stats['total_transactions']; ?></div>
                    <div class="stat-label">交易记录</div>
                </div>
            </div>
            <div class="settings-stat-item">
                <div class="stat-icon">💾</div>
                <div class="stat-content">
                    <div class="stat-value"><?php echo $stats['database_size']; ?> MB</div>
                    <div class="stat-label">数据库大小</div>
                </div>
            </div>
        </div>
    </div>
    <!-- 分页标签导航 -->
    <div class="settings-tabs">
        <div class="tab-nav">
            <button class="tab-btn active" data-tab="system">⚙️ 系统配置</button>
            <button class="tab-btn" data-tab="database">🗄️ 数据库管理</button>
            <button class="tab-btn" data-tab="users">👤 用户管理</button>
            <button class="tab-btn" data-tab="info">ℹ️ 系统信息</button>
        </div>

        <!-- 系统配置页面 -->
        <div class="tab-content active" id="system-tab">
            <div class="dashboard-card">
                <h3>⚙️ 系统配置</h3>
                <form method="POST" class="settings-form">
                    <input type="hidden" name="action" value="update_system">
                    <div class="settings-grid">
                        <div class="settings-section">
                            <h4>🏷️ 基本设置</h4>
                            <div class="form-group">
                                <label for="system_name">系统名称</label>
                                <input type="text" id="system_name" name="system_name" class="form-control"
                                    value="<?php echo htmlspecialchars($systemSettings['system_name'] ?? '玻璃包裹管理系统'); ?>" required>
                            </div>
                            <div class="form-group">
                                <label for="system_version">系统版本</label>
                                <input type="text" id="system_version" name="system_version" class="form-control"
                                    value="<?php echo htmlspecialchars($systemSettings['system_version'] ?? '1.0.0'); ?>">
                            </div>
                        </div>
                        
                        <div class="settings-section">
                            <h4>🔧 高级设置</h4>
                            <div class="form-group">
                                <div class="checkbox-wrapper">
                                    <input type="checkbox" id="maintenance_mode" name="maintenance_mode"
                                        <?php echo ($systemSettings['maintenance_mode'] ?? 0) ? 'checked' : ''; ?>>
                                    <label for="maintenance_mode">🚧 维护模式</label>
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="session_timeout">⏱️ 会话超时（分钟）</label>
                                <input type="number" id="session_timeout" name="session_timeout" class="form-control"
                                    value="<?php echo htmlspecialchars($systemSettings['session_timeout'] ?? 30); ?>" min="5" max="1440">
                            </div>
                        </div>
                    </div>
                    <div class="form-actions">
                        <button type="submit" class="btn btn-primary">💾 保存设置</button>
                    </div>
                </form>
            </div>
        </div>

        <!-- 数据库管理页面 -->
        <div class="tab-content" id="database-tab">
            <div class="dashboard-card">
                <h3>🗄️ 数据库管理</h3>
                <div class="settings-grid">
                    <div class="settings-section">
                        <h4>💾 数据库备份</h4>
                        <form method="POST" class="backup-form">
                            <input type="hidden" name="action" value="backup_database">
                            <p class="section-description">创建数据库的完整备份，建议定期执行以确保数据安全。</p>
                            <button type="submit" class="btn btn-warning" onclick="return confirm('确定要备份数据库吗？');">📥 创建备份</button>
                        </form>

                        <?php if (!empty($backupFiles)): ?>
                            <div class="backup-list">
                                <h5>📁 备份文件列表</h5>
                                <?php foreach (array_slice($backupFiles, 0, 5) as $file): ?>
                                    <div class="backup-item">
                                        <span class="backup-name">📄 <?php echo htmlspecialchars($file); ?></span>
                                        <span class="backup-time"><?php echo date('m-d H:i', filemtime('../backups/' . $file)); ?></span>
                                    </div>
                                <?php endforeach; ?>
                                <?php if (count($backupFiles) > 5): ?>
                                    <p class="backup-more">还有 <?php echo count($backupFiles) - 5; ?> 个备份文件...</p>
                                <?php endif; ?>
                            </div>
                        <?php endif; ?>
                    </div>
                    
                    <div class="settings-section">
                        <h4>🧹 日志清理</h4>
                        <form method="POST" class="cleanup-form">
                            <input type="hidden" name="action" value="clear_logs">
                            <p class="section-description">清理指定天数之前的交易日志，释放数据库空间。</p>
                            <div class="form-group">
                                <label for="days_to_keep">📅 保留天数</label>
                                <input type="number" id="days_to_keep" name="days_to_keep" value="30" min="1" max="365" class="form-control">
                            </div>
                            <button type="submit" class="btn btn-danger" onclick="return confirm('确定要清理日志吗？此操作不可恢复！');">🗑️ 清理日志</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>

        <!-- 用户管理页面 -->
        <div class="tab-content" id="users-tab">
            <div class="dashboard-card">
                <h3>👤 用户密码重置</h3>
                <form method="POST" class="password-reset-form">
                    <input type="hidden" name="action" value="reset_password">
                    <div class="settings-grid">
                        <div class="settings-section">
                            <h4>🎯 选择用户</h4>
                            <div class="form-group">
                                <label for="user_id">👥 用户列表</label>
                                <select id="user_id" name="user_id" class="form-control" required>
                                    <option value="">请选择用户</option>
                                    <?php foreach ($users as $user): ?>
                                        <option value="<?php echo $user['id']; ?>">
                                            <?php echo htmlspecialchars($user['username'] . ' - ' . ($user['real_name'] ?: '未设置') . ' (' . $user['role'] . ')'); ?>
                                        </option>
                                    <?php endforeach; ?>
                                </select>
                            </div>
                        </div>
                        
                        <div class="settings-section">
                            <h4>🔒 设置新密码</h4>
                            <div class="form-group">
                                <label for="new_password">🔑 新密码</label>
                                <input type="password" id="new_password" name="new_password" class="form-control"
                                    minlength="6" required placeholder="至少6位字符">
                            </div>
                        </div>
                    </div>
                    <div class="form-actions">
                        <button type="submit" class="btn btn-warning" onclick="return confirm('确定要重置该用户的密码吗？');">🔄 重置密码</button>
                    </div>
                </form>
            </div>
        </div>

        <!-- 系统信息页面 -->
        <div class="tab-content" id="info-tab">
            <div class="dashboard-card">
                <h3>ℹ️ 系统信息</h3>
                <div class="system-info-grid">
                    <div class="info-section">
                        <h4>🖥️ 服务器信息</h4>
                        <div class="info-list">
                            <div class="info-item">
                                <span class="info-label">PHP版本:</span>
                                <span class="info-value"><?php echo PHP_VERSION; ?></span>
                            </div>
                            <div class="info-item">
                                <span class="info-label">服务器软件:</span>
                                <span class="info-value"><?php echo $_SERVER['SERVER_SOFTWARE'] ?? 'Unknown'; ?></span>
                            </div>
                            <div class="info-item">
                                <span class="info-label">操作系统:</span>
                                <span class="info-value"><?php echo PHP_OS; ?></span>
                            </div>
                            <div class="info-item">
                                <span class="info-label">内存限制:</span>
                                <span class="info-value"><?php echo ini_get('memory_limit'); ?></span>
                            </div>
                        </div>
                    </div>
                    
                    <div class="info-section">
                        <h4>🗄️ 数据库信息</h4>
                        <div class="info-list">
                            <div class="info-item">
                                <span class="info-label">数据库类型:</span>
                                <span class="info-value">MySQL</span>
                            </div>
                            <div class="info-item">
                                <span class="info-label">数据库主机:</span>
                                <span class="info-value"><?php echo DB_HOST; ?></span>
                            </div>
                            <div class="info-item">
                                <span class="info-label">数据库名称:</span>
                                <span class="info-value"><?php echo DB_NAME; ?></span>
                            </div>
                            <div class="info-item">
                                <span class="info-label">字符集:</span>
                                <span class="info-value">UTF-8</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
// 标签页切换功能
document.addEventListener('DOMContentLoaded', function() {
    const tabBtns = document.querySelectorAll('.tab-btn');
    const tabContents = document.querySelectorAll('.tab-content');

    tabBtns.forEach(btn => {
        btn.addEventListener('click', function() {
            const targetTab = this.getAttribute('data-tab');
            
            // 移除所有活动状态
            tabBtns.forEach(b => b.classList.remove('active'));
            tabContents.forEach(c => c.classList.remove('active'));
            
            // 添加当前活动状态
            this.classList.add('active');
            document.getElementById(targetTab + '-tab').classList.add('active');
        });
    });

    // 自动刷新时间显示
    function updateTime() {
        const now = new Date();
        const timeString = now.toLocaleString('zh-CN');
        document.title = '系统设置 - ' + timeString;
    }

    setInterval(updateTime, 1000);
    updateTime();

    // 表单验证
    const forms = document.querySelectorAll('form');
    forms.forEach(form => {
        form.addEventListener('submit', function(e) {
            const requiredFields = form.querySelectorAll('[required]');
            let isValid = true;

            requiredFields.forEach(field => {
                if (!field.value.trim()) {
                    field.style.borderColor = '#e74c3c';
                    isValid = false;
                } else {
                    field.style.borderColor = '#ddd';
                }
            });

            if (!isValid) {
                e.preventDefault();
                alert('请填写所有必填字段');
            }
        });
    });
});
</script>
<?php
$content = ob_get_clean();
// 渲染页面
echo renderAdminLayout('系统设置', $content, $currentUser, 'settings.php', $additionalCSS, [], $message ?? '', $messageType ?? 'info');
?>